// Hand-written Deno helper. Unlike _shared/, nothing here is generated.

/**
 * Confirms a scheduled function was called by the scheduler.
 *
 * The platform's JWT check is not sufficient on its own: the token the cron
 * presents is the publishable anon key, which ships in the app bundle and is
 * committed to the repository, so anyone could invoke these functions.
 * Idempotence bounds what a repeated call writes but not what it does — a
 * loop on fetch-cbn-rates would hammer an undocumented upstream endpoint from
 * this project's IP, and one on check-rate-health would push a notification
 * to the Admin's phone every time.
 *
 * The secret lives in Vault, generated by the database, and is read here with
 * the service-role client. It never appears in the repository.
 */

// deno-lint-ignore no-explicit-any
export async function calledByScheduler(
  request: Request,
  supabase: any
): Promise<boolean> {
  const presented = request.headers.get('x-canji-cron');
  if (!presented) return false;

  // Compared inside the database. Reading the vault through the client does
  // not work — PostgREST only exposes configured schemas, and the vault
  // schema is deliberately not one — and this is better regardless: the
  // secret never crosses the API boundary, only a boolean does.
  const { data, error } = await supabase.rpc('verify_cron_secret', {
    presented,
  });

  return !error && data === true;
}

export function refuse(): Response {
  // Deliberately says nothing about why. A caller probing these endpoints
  // learns only that they are closed.
  return new Response(JSON.stringify({ error: 'Not found.' }), {
    status: 404,
    headers: { 'Content-Type': 'application/json' },
  });
}
